# 1) Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.
 

In [23]:
name = "Vishal"
age = 20
print("name : " + name)
print("age : " + str(age))

name : Vishal
age : 20


# 2) X="Datascience is used to extract meaningful insights." Split the string

In [2]:
X="Datascience is used to extract meaningful insights."
l = X.split(" ")
print(l)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


# 3) Make a function that gives multiplication of two numbers

In [3]:
def multiply(x, y):
    return x*y
print(multiply(10, 20))

200


# 4) Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [7]:
dictionary = {"TamilNadu" : "Chennai",
             "Maharashtra" : "Mumbai",
             "Telengana" : "Hyderabad",
             "Kerala" : "Tiruvanandapuram",
             "Karnataka" : "Bangalore"}
print(dictionary)
print(dictionary.keys())
print(dictionary.values())

{'TamilNadu': 'Chennai', 'Maharashtra': 'Mumbai', 'Telengana': 'Hyderabad', 'Kerala': 'Tiruvanandapuram', 'Karnataka': 'Bangalore'}
dict_keys(['TamilNadu', 'Maharashtra', 'Telengana', 'Kerala', 'Karnataka'])
dict_values(['Chennai', 'Mumbai', 'Hyderabad', 'Tiruvanandapuram', 'Bangalore'])


# 5) Create a list of 1000 numbers using range function.

In [ ]:
l = [i for i in range(1, 1001)]
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

# 6) Create an identity matrix of dimension 4 by 4

In [10]:
import numpy as np
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 7) Create a 3x3 matrix with values ranging from 1 to 9

In [11]:
n = np.arange(1,10).reshape(3,3)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 8) Create 2 similar dimensional array and perform sum on them.

In [15]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(a + b)

[[ 6  8]
 [10 12]]


# 9) Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [17]:
from datetime import timedelta, date
import pandas as pd
dates = []
def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

start_dt = date(2023, 2, 1)
end_dt = date(2023, 3, 1)
for dt in daterange(start_dt, end_dt):
    dates.append(dt.strftime("%Y-%m-%d"))
dates = pd.Series(dates)
print(dates)

0     2023-02-01
1     2023-02-02
2     2023-02-03
3     2023-02-04
4     2023-02-05
5     2023-02-06
6     2023-02-07
7     2023-02-08
8     2023-02-09
9     2023-02-10
10    2023-02-11
11    2023-02-12
12    2023-02-13
13    2023-02-14
14    2023-02-15
15    2023-02-16
16    2023-02-17
17    2023-02-18
18    2023-02-19
19    2023-02-20
20    2023-02-21
21    2023-02-22
22    2023-02-23
23    2023-02-24
24    2023-02-25
25    2023-02-26
26    2023-02-27
27    2023-02-28
28    2023-03-01
dtype: object


# 10) Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [19]:
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
