In [8]:
#1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.
a = "Edil Auxillea A"
b = 19

print("My name is", a)
print("My age is", b)

My name is Edil Auxillea A
My age is 19


In [9]:
#2. X="Datascience is used to extract meaningful insights." Split the string
a = "Datascience is used to extract meaningful insights."
b = a.split()
print(b)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [10]:
#3. Make a function that gives multiplication of two numbers
def mul():
    a = float(input("Enter number 1: "))
    b = float(input("Enter number 2: "))
    return a*b
ans = mul()
print("The multiplication result is:", ans)

Enter number 1: 3
Enter number 2: 3
The multiplication result is: 9.0


In [11]:
#4. Create a Dictionary of 5 States with their capitals. also print the keys and values.
a = {
    "Andhra Pradesh": "Hyderabad",
    "Jharkhand": "Ranchi",
    "Karnataka": "Bengaluru",
    "Kerala": "Thiruvananthapuram",
    "Tamil Nadu": "Chennai"
}

print("States:")
for b in a.keys():
    print(b)

print("\nCapitals:")
for c in a.values():
    print(c)

States:
Andhra Pradesh
Jharkhand
Karnataka
Kerala
Tamil Nadu

Capitals:
Hyderabad
Ranchi
Bengaluru
Thiruvananthapuram
Chennai


In [12]:
#5. Create a list of 1000 numbers using range function.
a = list(range(1, 1001))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [13]:
#6. Create an identity matrix of dimension 4 by 4
import numpy as np
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#7. Create a 3x3 matrix with values ranging from 1 to 9
import numpy as np
x =  np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#8. Create 2 similar dimensional array and perform sum on them.
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

array1 = []
print("Enter the elements of the first array:")
for i in range(rows):
    row = []
    for j in range(cols):
        element = int(input(f"({i}, {j}): "))
        row.append(element)
    array1.append(row)

array2 = []
print("Enter the elements of the second array:")
for i in range(rows):
    row = []
    for j in range(cols):
        element = int(input(f"({i}, {j}): "))
        row.append(element)
    array2.append(row)

sum_array = []
for i in range(rows):
    row = []
    for j in range(cols):
        element_sum = array1[i][j] + array2[i][j]
        row.append(element_sum)
    sum_array.append(row)

print("Sum array:")
for row in sum_array:
    print(row)


Enter the number of rows: 2
Enter the number of columns: 3
Enter the elements of the first array:
(0, 0): 4
(0, 1): 5
(0, 2): 3
(1, 0): 2
(1, 1): 1
(1, 2): 3
Enter the elements of the second array:
(0, 0): 0
(0, 1): 9
(0, 2): 3
(1, 0): 4
(1, 1): 8
(1, 2): 6
Sum array:
[4, 14, 6]
[6, 9, 9]


In [16]:
#9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

current_date = start_date
while current_date <= end_date:
    print(current_date.strftime("%d-%m-%Y"))
    current_date += timedelta(days=1)

01-02-2023
02-02-2023
03-02-2023
04-02-2023
05-02-2023
06-02-2023
07-02-2023
08-02-2023
09-02-2023
10-02-2023
11-02-2023
12-02-2023
13-02-2023
14-02-2023
15-02-2023
16-02-2023
17-02-2023
18-02-2023
19-02-2023
20-02-2023
21-02-2023
22-02-2023
23-02-2023
24-02-2023
25-02-2023
26-02-2023
27-02-2023
28-02-2023
01-03-2023


In [18]:
'''
10. Given a dictionary, convert it into corresponding dataframe and display it
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
'''
import pandas as pd
a = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
b = pd.DataFrame(a)
print(b)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
